language: python
matrix:
  fast_finish: true
jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "pypy"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: "python setup.py test"

# Automated Deployment to Artifactory
deploy:
  provider: pypi
  user: $ARTIFACTORY_USERNAME # Both the Artifactory username and password are stored in Travis CI Environment Variables
  password: $ARTIFACTORY_PASSWORD
  server: https://mdsol.jfrog.io/mdsol/api/pypi/pypi-local
  on:
    tags: true
    python: 3.7
  distributions: sdist bdist_wheel
