language: python
cache: pip

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

before_install:
  - pip install poetry
  - pip install tox-travis

install:
  - poetry install -v

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      python: 3.8
      script:
        - poetry run flake8 --version
        - poetry run flake8

script:
  - tox

before_deploy:
  - poetry config repositories.mdsol https://mdsol.jfrog.io/mdsol/api/pypi/pypi-local
  - poetry config http-basic.mdsol $ARTIFACTORY_USERNAME $ARTIFACTORY_PASSWORD # Stored as Travis CI Environment Vars
  - poetry build

deploy:
  provider: script
  script: poetry publish -r mdsol
  on:
    tags: true
    python: 3.8
