dist: focal
language: python
cache: pip

python:
  - 3.7.13 # specify micro version to avoid having EnvCommandError
  - 3.8
  - 3.9
  - 3.10

before_install:
  - pip install poetry==1.1.15 # latest poetry 1.1.20 was having problems with travis
  - pip install tox-travis

install: poetry install -v

script: tox

stages:
  - lint
  - test
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: lint
      python: 3.10
      script:
        - poetry run flake8 --version
        - poetry run flake8
    - stage: publish
      python: 3.10
      script: skip
      before_deploy:
        - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI  # this may be unnecessary
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
