name: Check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install poetry
        run: pipx install poetry==2.2.1
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction
      - run: poetry run flake8

  test:
    name: 🧪 ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest
          - os: macOS
            image: macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Install poetry
        run: pipx install poetry==2.2.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: python-setup
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Set poetry environment
        run: poetry env use ${{ steps.python-setup.outputs.python-path }}
      - name: Install dependencies
        run: poetry install --no-interaction
      - run: poetry run pytest
