name: Check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install poetry
        run: pipx install poetry==2.4.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-interaction
      - run: poetry run flake8

  test:
    name: 🧪 ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu, macOS, Windows]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest
          - os: macOS
            image: macos-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Install poetry
        run: pipx install poetry==2.4.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: python-setup
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Set poetry environment
        run: poetry env use ${{ steps.python-setup.outputs.python-path }}
      - name: Install dependencies
        run: poetry install --no-interaction
      - run: poetry run pytest

  pypy:
    name: Ubuntu / PyPy 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Install Poetry
        run: pipx install poetry==2.4.1
      - name: Set up PyPy 3.10
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: pypy-setup
        with:
          python-version: pypy3.10
          cache: 'poetry'
      - name: Set Poetry environment
        run: poetry env use ${{ steps.pypy-setup.outputs.python-path }}
      - name: Install dependencies
        run: poetry install --no-interaction
      - run: poetry run pytest
